### ISSUE TITLE
Items being duplicated when entering scenes

### ISSUE THREAD

**Issue by LittleAstroid** [heatdeathnow/FacingDemons#2]
Caused by scene.items array.

Suggested fix for Scenes.py:

```py
 if self.items:
            GUI.linebreak(15)
            print(f"Rummaging through this room, you've found a {self.items}")
            print("You have collected the item and it's now in your inventory.")
            input()

            Items.itemadd(self.items)
            self.items = None
```

**Comment by LittleAstroid** [comment]
This was fixed on 77cba424e4584667b500402fef32c0e268c298eb. (Use um nome diferente pro commit, seu maldito)

**Comment by heatdeathnow** [comment]
https://github.com/heatdeathnow/FacingDemons/commit/77cba424e4584667b500402fef32c0e268c298eb
Eu não sei como essa caralha funciona.
